### ISSUE TITLE
buttersink uses wrong sizes when finding best sync path

### ISSUE THREAD

**Issue by youam** [AmesCornish/buttersink#14]
I've got a number of snapshots, which are daily rsyncs of a directory tree, where sometimes I delete the rsync destination, so that for most days, snapN and snapN+1 are nearly identical, but when I want a "full" rsync backup, snapN and snapN+1 contain nearly-identical files, but because I rsynced against an empty destination instead of yesterdays, the actual btrfs file extends are completely different, for example:

```
name   size   diff to yesterday
day01  500MB  ./.
day02  510MB  50MB
day03  505MB  40MB
day04  490MB  490MB  <<<
day05  505MB  40MB
```

Now, I'd think the best diff algorithm figures out that there's two different clusters day01..day03 and day04..day05 where all diffs between two days in a cluster are fairly small, and diffs from one cluster to the next are fairly large and should be avoided. But that's not what I see. Instead, buttersink selects one day (which looks fairly random to me), e.g. day04, and transmits that in full. then, it selects some other day and diffs that against the transmitted day04, e.g. day05. those two days are in the same cluster of days, and everything is fine, it transfers about 40mb.

But when it figures out the diff size between days in one cluster and the other, something wrong happens. the size I'm shown looks like it does an actual /usr/bin/diff between the two snapshots, instead of an btrfs send, e.g. an estimated size of ~30MB between day04 and day03, instead of the actual 505MB, as day03 and day04 don't share any extends.

Of course, that's throwing the full algorithm off, and I end up with lots of wasted (time and) space on the destination filesystem:

```
 Xfer: 5e6d...4d48 /srv/backup/snapshot/youam.de/cailin.int.youam.de/2015-11-04T03:32:25+0000 from a676...44b4 /srv/backup/snapshot/youam.de/cailin.int.youam.de/2015-11-03T03:38:03+0000 (~5.242 MiB)
0:00:01.387560: Sent 4.566 MiB of 5.242 MiB (87%) ETA: 0:00:00.205553 (27.6 Mbps )                     
 Xfer: d27b...2f40 /srv/backup/snapshot/youam.de/cailin.int.youam.de/2015-11-11T03:45:01+0000 from aba1...e172 /srv/backup/snapshot/youam.de/cailin.int.youam.de/2015-11-09T05:36:57+0000 (~2.196 MiB)
0:00:19.540641: Sent 145.5 MiB of 2.196 MiB (6624%) ETA: None (62.5 Mbps )                     
```

I'm seeing this happen both with the --estimate flag and without it. What am I doing wrong here? (btrfs quota was not used at snapshot creation time and was only enabled by buttersink itself, if that matters)

**Comment by AmesCornish** [comment]
youam,

Are you transferring locally, or to a remote ssh, or to S3?
- Ames

## 

Ames Cornish  ~  http://montebellopartners.com/
650-533-0835  ~  ames@montebellopartners.com

**Comment by youam** [comment]
I'm transferring locally

**Comment by AmesCornish** [comment]
By design, buttersink never measures for local transfers.  This is because measuring takes essentially the same amount of time as transferring, so doing a lot of measurement before deciding on transfers could take many times longer than just transferring based on (even incorrect) estimates.

I do see your point about potentially wasting space on the destination with this design.  If you use a (local) ssh connection for the transfer (and don't specify the --estimate flag), I think you'll get the behavior you're looking for.  If you try this, please let me know whether you like it.  It might be worth adding a flag to buttersink to specify this behavior more directly.

Another possibility would be to dedup your snapshots before using buttersink.  `duperemove` is one utility that could do this.

Thanks for the feedback!

**Comment by youam** [comment]
Thanks for the tip with the local ssh connection. From the output, it looks better. It figures out, that the estimates are way to low, and retries different diffs. But then the transmission of the diff fails, any hint about that? :) The command is called as 

```
sudo buttersink -l /tmp/bs.log /srv/backup/snapshot/youam.de/adara.int.youam.de/ ssh://root@breandan/media/offbackup3/snapshot/youam.de/adara.int.youam.de/
```

with a passwordless ssh key, and takes a bit over four minutes to start transmitting, but the ssh logs don't look like it's an ssh problem?

```
2015-11-17 08:32:30,116:   DEBUG:Butter.py[110]: Command: ['btrfs', 'send', '-p', u'/srv/backup/snapshot/youam.de/adara.int.youam.de/2015-11-15T11:41:51+0000', u'/srv/backup/snapshot/youam.de/adara.int.youam.de/2015-11-14T03:41:10+0000']
2015-11-17 08:32:43,302:   DEBUG:send.py[180]: Setting received df7d23f7-6075-dd4c-9e6c-85999a7c5dd6/503598 and parent 1434693e-7d3b-c14f-ba5f-46833b9de292/504233
2015-11-17 08:32:43,337:   DEBUG:send.py[190]: Version: 1
2015-11-17 08:32:43,338:   DEBUG:send.py[198]: Command: 2
2015-11-17 08:32:43,339:   DEBUG:send.py[295]: Snapshot: 1434693e-7d3b-c14f-ba5f-46833b9de292/504233 -> df7d23f7-6075-dd4c-9e6c-85999a7c5dd6/503598 2015-11-14T03:41:10+0000
2015-11-17 08:32:45,030:   DEBUG:Butter.py[226]: Waiting for send process to finish...
2015-11-17 08:32:45,031:   ERROR:Butter.py[230]: btrfs send errors
2015-11-17 08:32:45,044:   DEBUG:SSHStore.py[125]: Secondary error: {u'traceback': u'  File "/usr/local/lib/python2.7/dist-packages/buttersink/Butter.py", line 179, in __exit__', u'errorType': u'Exception', u'command': u'write', u'server': True, u'error': u'receive /media/offbackup3/snapshot/youam.de/adara.int.youam.de/2015-11-14T03:41:10+0000 returned error 1.'}
2015-11-17 08:32:45,046:   DEBUG:SSHStore.py[361]: Waiting for ssh process to finish...
2015-11-17 08:32:45,100:   DEBUG:buttersink.py[268]: Trace information for debugging
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/buttersink/buttersink.py", line 251, in main
    diff.sendTo(dest, chunkSize=args.part_size << 20)
  File "/usr/local/lib/python2.7/dist-packages/buttersink/Store.py", line 352, in sendTo
    transfer(sendContext, receiveContext, chunkSize)
  File "/usr/local/lib/python2.7/dist-packages/buttersink/Store.py", line 274, in transfer
    writer.write(data)
  File "/usr/local/lib/python2.7/dist-packages/buttersink/SSHStore.py", line 156, in write
    raise Exception(result)
Exception: {u'traceback': u'  File "/usr/local/lib/python2.7/dist-packages/buttersink/Butter.py", line 193, in write', u'errorType': u'IOError', u'command': u'write', u'server': True, u'error': u'[Errno 32] Broken pipe'}
2015-11-17 08:32:45,103:   ERROR:buttersink.py[269]: ERROR: {u'traceback': u'  File "/usr/local/lib/python2.7/dist-packages/buttersink/Butter.py", line 193, in write', u'errorType': u'IOError', u'command': u'write', u'server': True, u'error': u'[Errno 32] Broken pipe'}.
```

**Comment by youam** [comment]
uhm. okay, this is something else. calling buttersink locally also fails, and even calling `btrfs send | btrfs receive` directly fails:

```
$ sudo btrfs send -p /srv/backup/snapshot/youam.de/adara.int.youam.de/2015-11-15T11:41:51+0000 /srv/backup/snapshot/youam.de/adara.int.youam.de/2015-11-14T03:41:10+0000 | sudo btrfs receive -e /media/offbackup3/snapshot/youam.de/adara.int.youam.de
At subvol /srv/backup/snapshot/youam.de/adara.int.youam.de/2015-11-14T03:41:10+0000
At snapshot 2015-11-14T03:41:10+0000
ERROR: truncate .rsync-filter failed. No such file or directory
```

all snapshots on the destination file system were created by buttersink, except for this test run. This looks like a data corruption bug. Even better, the .rsync-filter file is unchanged between both snapshots (execpt for the accesstime). Something's very fishy here...

**Comment by AmesCornish** [comment]
Youam,

You may be running into one of various btrfs tools and kernel bugs, for example:

http://forum.rockstor.com/t/apparent-issues-with-quotas-and-snapshots/252
http://www.spinics.net/lists/linux-btrfs/msg48968.html
https://www.mail-archive.com/search?l=linux-btrfs@vger.kernel.org&q=subject:%22Re%3A+btrfs+send+and+kernel+3.17%22&o=newest&f=1
https://github.com/markfasheh/duperemove/issues/50
http://www.spinics.net/lists/linux-btrfs/msg42279.html

These errors are not fully understood yet, but here are a few things to try to see if you can narrow down the problem:
- Do a rebalance: `sudo btrfs bal start <path>`
- Turn quota off: `sudo btrfs quota disable <path>`
  (of course buttersink will turn quota back on the next time it's run)
- Try a scrub: `sudo btrfs scrub start <path>`
- Try updating your kernel or btrfs tools

I'm opening a new issue #15 for this -- please reply there.  Thanks!

**Comment by youam** [comment]
Closing this issue, as my problem was explained by Ames to be the desired behavior for local transfers - which makes sense, and has a good workaround for forcing the behavior i expected. My following problems are independent of this, probably because of a broken source file system.
