### ISSUE TITLE
"No snapshots in source" across mountpoints

### ISSUE THREAD

**Issue by flungo** [AmesCornish/buttersink#16]
Whenever I try to use `buttersink` across mount points I get the error: "No snapshots in source."

Example command:

```
buttersink /mnt/ssd/.snapshots/ /mnt/hdd/.snapshots/
```

But it works fine inside the same mountpoint:

```
buttersink /mnt/ssd/.snapshots/ /mnt/hdd/.snapshots-2/
```

In these examples, /mnt/ssd and /mnt/hdd are the mountpoints of 2 separate disks.

The issue even occurs across mount points of the same disk, if (for example) `/dev/sda` was mounted in both `/mnt/sda1` and `/mnt/sda2/` and I were to run:

```
buttersink /mnt/sda1/.snapshots/ /mnt/sda2/.snapshots-2/
```

I would get the same error.

**Comment by AmesCornish** [comment]
Fabrizio,

Thanks for the report.  I'm definitely able to sync between different local devices and between different mounts of the same device with buttersink 0.6.7 and btrfs 4.2.2, so I'm having trouble reproducing your issue.  Could you post a "--logfile"?
- Ames

**Comment by flungo** [comment]
Can't reproduce again. Seems to be working now. Thanks.
