### ISSUE TITLE
Path /dir/of/dest/ exists, can't receive

### ISSUE THREAD

**Issue by holmesb** [AmesCornish/buttersink#18]
Hi,

Trying my first buttersink using command:
buttersink.py /dir/of/src/ ssh://user@dest_server/dir/of/dest/

> [user@src_server]# python /usr/lib/python2.7/site-packages/buttersink/buttersink.py /dir/of/src ssh://user@dest_server/dir/of/dest/ 
> user@src_server's password:
> Remote version: {u'btrfs': u'btrfs-progs v4.3.1', u'buttersink': u'0.6.7', u'linux': u'Linux-4.3.3-1.el7.elrepo.x86_64-x86_64-with-redhat-3.8.10-Core'}
> measured size (7.317 GiB), estimated size (7.317 GiB)
> Optimal synchronization:
> 7.317 GiB from 1 diffs in btrfs /dir/of/src
> 7.317 GiB from 1 diffs in TOTAL
> Xfer: edab...a1f1 /dir/of/src from None (7.317 GiB)
> ERROR: {u'traceback': u' File "/usr/lib/python2.7/site-packages/buttersink/ButterStore.py", line 179, in receive', u'errorType': u'Exception', u'command': u'receive', u'server': True, u'error': u"Path /dir/of/dest exists, can't receive edabab74-824e-ff48-bf2b-7f6a1de0a1f1"}

If I delete the destination path, it complains "S|ERROR: '/dir/of/dest' is not an existing directory". Any ideas?

**Comment by AmesCornish** [comment]
Are you trying to copy a single snapshot called `src`, or all the snapshots  in the `src` directory?  If the later, you need to change `/dir/of/src` to `/dir/of/src/` in your buttersink command line.

**Comment by holmesb** [comment]
Single snap.  I think I've fixed that now.  I was specifying the dir above the snap rather than the snap directory itself.  However now failing:

> [root@nas03 tmp]# python /usr/lib/python2.7/site-packages/buttersink/buttersink.py /dir/of/source ssh://root@dest_server/dir/of/dest/
> root@src_server's password:
>   Remote version: {u'btrfs': u'btrfs-progs v4.3.1', u'buttersink': u'0.6.7', u'linux': u'Linux-4.3.3-1.el7.elrepo.x86_64-x86_64-with-redhat-3.8.10-Core'}
>   measured size (7.317 GiB), estimated size (7.317 GiB)
>   Optimal synchronization:
>   7.317 GiB from 1 diffs in btrfs /dir/of/source
>   7.317 GiB from 1 diffs in TOTAL
>   Xfer: 47f8...1c7b /dir/of/source from None (7.317 GiB)
>   btrfs send errors
> At subvol /dir/of/source
> ERROR: failed to dump stream. Broken pipe
> 
>   ERROR: vars() argument must have **dict** attribute.

However, the command:

> btrfs send -v /dir/of/source | ssh dest_server btrfs receive /dir/of/dest/

works fine:

> [root@src_server tmp]# btrfs send -v /dir/of/source | ssh dest_server btrfs receive /dir/of/dest/
> At subvol /dir/of/source
> root@source_server's password:
> At subvol /source_dir
> BTRFS_IOC_SEND returned 0
> joining genl thread

**Comment by AmesCornish** [comment]
I'm not able to reproduce the second "Broken pipe" error.  I suspect it was a transient network or btrfs error.  If this is still a problem for you, could you re-test with buttersink 0.6.8 and send the log (using the `--logfile` argument)?  Thanks!
