### ISSUE TITLE
How does ssh syncing work?

### ISSUE THREAD

**Issue by ddurdle** [AmesCornish/buttersink#23]
I'm failing to understand if this requires an existing snapshot to be on the dst to sync or if it will handle the initial sync.  I'm trying to do a sync using ssh and if I select a pre-existing snapshot on the destination, it tells me it exists so cannot receive.  If select a non-existing name (for an initial sync), it tells me it cannot since it doesn't exist.  Really need an example that works using ssh.

```
t420-ssd t420 # buttersink -d boot.20150915/ ssh://root@192.168.1.138/btrfs/
root@192.168.1.138's password: 
  Remote version: {u'btrfs': u'Btrfs v3.17', u'buttersink': u'0.6.7', u'linux': u'Linux-4.4.1-sunxi-armv7l-with-debian-8.0'}
  measured size (110.3 MiB), estimated size (110.3 MiB)
  Optimal synchronization:
  110.3 MiB from 1 diffs in btrfs /btrfs/t420/boot.20150915
  110.3 MiB from 1 diffs in TOTAL
  Xfer: bcc4...9870 /btrfs/t420/boot.20150915 from None (110.3 MiB)
  ERROR: {u'traceback': u'  File "build/bdist.linux-armv7l/egg/buttersink/ButterStore.py", line 179, in receive', u'errorType': u'Exception', u'command': u'receive', u'server': True, u'error': u"Path /btrfs exists, can't receive bcc4fe8d-3573-2743-a16b-dd77b7279870"}.
t420-ssd t420 # buttersink -d boot.20150915/ ssh://root@192.168.1.138/btrfs/test
root@192.168.1.138's password: 
S|ERROR: '/btrfs/test' is not an existing directory.

  ERROR: Fatal remote ssh server error.
t420-ssd t420 # buttersink -d boot.20150915/ ssh://root@192.168.1.138/btrfs/test/
root@192.168.1.138's password: 
S|ERROR: '/btrfs/test' is not an existing directory.

  ERROR: Fatal remote ssh server error.
t420-ssd t420 # buttersink -d boot.20150915/ ssh://root@192.168.1.138/btrfs/cubie-home.20160413
root@192.168.1.138's password: 
S|ERROR: '/btrfs/cubie-home.20160413' is not an existing directory.

  ERROR: Fatal remote ssh server error.
t420-ssd t420 # buttersink -d boot.20150915/ ssh://root@192.168.1.138/btrfs/cubie-home.20150413/
root@192.168.1.138's password: 
  Remote version: {u'btrfs': u'Btrfs v3.17', u'buttersink': u'0.6.7', u'linux': u'Linux-4.4.1-sunxi-armv7l-with-debian-8.0'}
  measured size (110.3 MiB), estimated size (110.3 MiB)
  Optimal synchronization:
  110.3 MiB from 1 diffs in btrfs /btrfs/t420/boot.20150915
  110.3 MiB from 1 diffs in TOTAL
  Xfer: bcc4...9870 /btrfs/t420/boot.20150915 from None (110.3 MiB)
  ERROR: {u'traceback': u'  File "build/bdist.linux-armv7l/egg/buttersink/ButterStore.py", line 179, in receive', u'errorType': u'Exception', u'command': u'receive', u'server': True, u'error': u"Path /btrfs/cubie-home.20150413 exists, can't receive bcc4fe8d-3573-2743-a16b-dd77b7279870"}.

```

**Comment by ddurdle** [comment]
I synced the initial across using send|receive and it looks like buttersink worked on syncing on subsequent run.  So, you cannot use buttersink for an initial sink, only on subsequent resync if the initial sync did not complete?

`t420-ssd t420 # btrfs send boot.20150915 | ssh root@192.168.1.138 "btrfs receive /btrfs/"
At subvol boot.20150915
root@192.168.1.138's password: 
At subvol boot.20150915

t420-ssd t420 # 
t420-ssd t420 # 
t420-ssd t420 # buttersink -d boot.20150915/ ssh://root@192.168.1.138/btrfs/boot.20150915/
root@192.168.1.138's password: 
  Remote version: {u'btrfs': u'Btrfs v3.17', u'buttersink': u'0.6.7', u'linux': u'Linux-4.4.1-sunxi-armv7l-with-debian-8.0'}
  measured size (0 bytes), estimated size (0 bytes)
  Optimal synchronization:
  100.3 MiB from 1 diffs in ssh://root@192.168.1.138/btrfs/boot.20150915
  100.3 MiB from 1 diffs in TOTAL
  Keep: bcc4...9870 /btrfs/boot.20150915 from None (100.3 MiB)
`

**Comment by AmesCornish** [comment]
The issue is that you were trying to sync the directory `boot.20150915/`, which does not contain any snapshots.  If you specify `boot.20150915` (without the trailing slash), buttersink will know you mean to transfer just the one snapshot.  Release 0.6.8 will contain an informative error message for this situation.  Thanks for the report!
