### ISSUE TITLE
buttersink seems to give wrong results when quota rescan is in progress

### ISSUE THREAD

**Issue by a3nm** [AmesCornish/buttersink#25]
I have a btrfs filesystem where I enabled quota with btrfs quota enable PATH.

The quota rescan is in progress, as evidenced by:

```
$ sudo btrfs quota rescan PATH
ERROR: quota rescan failed: Operation now in progress
```

However, running ./buttersync.py PATH/subvolumes (where subvolumes is a folder of the filesystem containing snapshots) happily succeeds and reports size for each subvolume. The sizes are bogus, and they keep increasing each time I run the command.

Shouldn't buttersink wait for quota rescan to be completed, the same way that it does when it takes itself the initiative of enabling quota?

**Comment by AmesCornish** [comment]
Indeed it should.  Fix will be in 0.6.8
