### ISSUE TITLE
Psutil error in Ubuntu 14.04 LTS

### ISSUE THREAD

**Issue by zetasyanthis** [AmesCornish/buttersink#3]
Looks like a newer version of the library is required for that ionice call...  Perhaps it'd be a good idea to make it optional and throw a warning if the system version of psutil doesn't support that?  (If you think that might be a good idea, I can fork and then submit a pull request with the changes at some stage...)

Traceback:

zeta@zetaX220:~$ sudo buttersink /media/bulkdata/test/.snapshots/ ssh://root@zetaserver/mnt/pool/testing_subvol/
root@zetaserver's password: 
  Remote version: {u'btrfs': u'Btrfs v3.14.1', u'buttersink': u'0.6', u'linux': u'Linux-3.13.0-48-generic-x86_64-with-Ubuntu-14.04-trusty'}

Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/buttersink/buttersink.py", line 233, in main
    best.analyze(args.part_size << 20, source, dest)
  File "build/bdist.linux-x86_64/egg/buttersink/BestDiffs.py", line 143, in analyze
    edge.sink.measureSize(edge, chunkSize)
  File "build/bdist.linux-x86_64/egg/buttersink/ButterStore.py", line 209, in measureSize
    allowDryRun=False,
  File "build/bdist.linux-x86_64/egg/buttersink/Butter.py", line 109, in send
    ps.ionice(psutil.IOPRIO_CLASS_IDLE)
AttributeError: 'Process' object has no attribute 'ionice'

Python and psutil versions:

zeta@zetaX220:~/repos/projects/buttersink$ python
Python 2.7.6 (default, Mar 22 2014, 22:59:56) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.

> > > import psutil
> > > psutil.**version**
> > > '1.2.1'

(As a secondary note, I've already updated btrfs-tools to 3.14, as the repository version in 14.04 is only 3.12.)

**Comment by AmesCornish** [comment]
Zeta,

Thanks for finding, id'ing, and offering to fix the bug.  The fix was pretty simple, so I just pushed a change that just ignores the error if ionice isn't available.  I'd rather not add a new option, since I think software should just do-the-right-thing whenever possible.  Please let me know if it fixes your issue.

Thanks!

**Comment by zetasyanthis** [comment]
That's exactly the change I made to get it running locally.  Looks good, and thanks!  :)
