### ISSUE TITLE
Are quotas required?

### ISSUE THREAD

**Issue by GrahamCobb** [AmesCornish/buttersink#30]
I was about to start experimenting with buttersink. I first tried btrfslist but I cancelled it when it said it was doing a quota scan.  I don't need quotas and don't have them enabled.  And from the warnings from btrfs people, I don't want them enabled, or anything to do with them.

I then wondered whether buttersink requires quotas?

**Comment by AmesCornish** [comment]
Yes, quotas are required to get the size of snapshots, which buttersink needs to plan its diffs.  I agree I've seen quite a few btrfs bugs around quotas, but the recent versions seem much better.

**Comment by GrahamCobb** [comment]
Thanks!  May be worth noting this somewhere in the README.
