### ISSUE TITLE
Buttersink fails with an error

### ISSUE THREAD

**Issue by hatramatra** [AmesCornish/buttersink#31]
Hello,

I'm trying to copy dirvish archive to another host but it fails with an error ...

root@giles:/media# buttersink -l /tmp/buttersink.log /media/btrfs/ ssh://viki.net.e-net.sk/mnt/btrfs/
  Remote version: {u'btrfs': u'Btrfs v3.17', u'buttersink': u'0.6.8', u'linux': u'Linux-3.16.0-4-amd64-x86_64-with-glibc2.4'}
  measured size (477.4 GiB), estimated size (477.4 GiB)
  Optimal synchronization:
  477.4 GiB from 140 diffs in btrfs /media/btrfs
  477.4 GiB from 140 diffs in TOTAL
  Xfer: 09b1...e2be /media/btrfs/dirvish/iptv-mcast/20160729-0244/tree from None (8.527 MiB)
 0:00:00.500888: Sent 11.75 MiB of 8.527 MiB (137%) ETA: None (197 Mbps )  
  ERROR: {u'traceback': u'  File "/usr/local/lib/python2.7/dist-packages/crcmod/_crcfunpy.py", line 73, in _crc32r', u'errorType': u'TypeError', u'command': u'write', u'server': True, u'error': u'ord() expected string of length 1, but int found'}.

The debug log is attached. The messages are too cryptic for me ... is it possible to tell from the debug log file what went wrong, please? 

Cheers,
Martin

[buttersink_log.zip](https://github.com/AmesCornish/buttersink/files/392641/buttersink_log.zip)

**Comment by mswart** [comment]
Please, take a look at #13; it looks like the same issue.

**Comment by hatramatra** [comment]
Oh, I should have checked the closed issues. I've installed python-crcmod from jessie-backports and it works, now. For reference, I needed also to uninstall crcmod installed by pip, what happened automatically when I was installing buttersink by pip. This confused me a bit. Thank you very much!
