### ISSUE TITLE
Remove CRC?

### ISSUE THREAD

**Issue by NicoHood** [AmesCornish/buttersink#32]
Hi,
I currently try to install buttersink on archlinux from AUR. However it has another AUR dependency for the crcmod package. I have not looked at the code, but can't you use something else than crc? Like sha512sums? Wouldnt this also be safer? I might be totally wrong though.

Edit: the dependency list is also missing in the readme. It would be cool if you can add that and mark which deps are optional.

**Comment by AmesCornish** [comment]
buttersink needs crcmod because btrfs send and receive use crc -- sha would not be compatible.  The dependencies are listed in pip.txt, but I agree it would be nice to have some pointers in the readme.
