### ISSUE TITLE
stuck and eats 100% cpu

### ISSUE THREAD

**Issue by gaetanquentin** [AmesCornish/buttersink#38]
sometimes it is stuck in infinite loop and eats 100%cpu.

Can't kill it (KILL -9 do nothing), and a strace shows nothing, so it seems it does not call sys calls at all.

**Comment by AmesCornish** [comment]
Hard to debug this without more context.  It sounds like a hang in the btrfs subsystem, maybe during send or receive.  I'd check that you have the latest btrfs-progs, and a recent kernel.  It could also be due to corruption in the btrfs file system.

**Comment by eugene-bright** [comment]
I'm experiencing such kind of things on snapshot deletion.
[One old email thread](http://linux-btrfs.vger.kernel.narkive.com/JfhnKeDz/btrfs-subvolume-snapshot-hung-in-btrfs-commit-transaction) fully describes my symptoms.

**Comment by eugene-bright** [comment]
Buttersink relies on btrfs quota feature to estimate diff sizes. If btrfs quota is disabled then it will be enabled by buttersink (but it also seems to be enabled by default on newly created FS).
Snapshot deletion can cause performance issues if quote feature is enabled.
https://www.reddit.com/r/btrfs/comments/4qz1qd/problems_with_btrfs_quota/

It looks to be a btrfs bug.
We should workaround it by adding an option to buttersink to disable any size estimation.

**Comment by eugene-bright** [comment]
Quoting developers conversation
https://www.spinics.net/lists/linux-btrfs/msg74737.html

> Snapshot creation and backref walk (used in qgroup, relocation and
> extent deletion), are two conflicting workload in fact.
