### ISSUE TITLE
Can not use ~/.ssh/config and default identity file 

### ISSUE THREAD

**Issue by ceremcem** [AmesCornish/buttersink#42]
As a normal user, running `buttersink` with `sudo` prevents using `$HOME/.ssh/config` and `$HOME/.ssh/id_rsa*` and asks for password. 

(fix is on the way)

**Comment by AmesCornish** [comment]
Did you try the -E option to sudo?

**Comment by ceremcem** [comment]
nope?

**Comment by ceremcem** [comment]
If the following is what you suggest, it doesn't work: 

```
sudo -E buttersink/buttersink.py /mnt/erik/snapshots/ ssh://aea3/mnt/zencefil/snapshots
ssh: Could not resolve hostname aea3: Name or service not known
  
  ERROR: Fatal remote ssh server error.
```

**Comment by AmesCornish** [comment]
The above error message is about aea3.  Does this give the same error message:

`sudo -E ssh aea3`

If so, you should troubleshoot that first.  Perhaps you need a fully-qualified host name?  Or a `user@aea3`?

**Comment by ceremcem** [comment]
`aea3` is defined in `~/.ssh/config`. I can't get what `sudo -E` should provide: 

```bash
diff <( sudo -E env ) <( sudo env )
< PWD=/home/ceremcem
< HOME=/home/ceremcem
< _=/usr/bin/sudo
---
42a12,13
> HOME=/root
```
