### ISSUE TITLE
--part-size improvements

### ISSUE THREAD

**Issue by crusaderky** [AmesCornish/buttersink#48]
There's a few problems with the --part-size setting:

1. the argparse help is improvable. I have no idea about what the default size is, and there is no indication that the amount is expressed in MBs and not in bytes. I had to read the source code to find out.
2. default size of 20MB is, IMHO, way too small, doesn't offer any real benefit, and significantly slows down upload. Amazon recommends 100MB.
3. S3 has a hard limit of 10,000 parts in a multipart upload. I discovered that when everything fell over after uploading 200 GB of data (aaaargh). Ideally, part-size should automatically adjust itself upwards when uploading large files (after printing a message), so that the limit is never hit.

**Comment by AmesCornish** [comment]
Good points.  I'll implement at least #1 and #2 shortly.
