### ISSUE TITLE
Refactoring: automated unit testing

### ISSUE THREAD

**Issue by eugene-bright** [AmesCornish/buttersink#57]
It's crucial to add some unit tests for data serialization/deserialization.
Hard to refactor this area without fast feedback.

**Comment by AmesCornish** [comment]
There is a suite of regression tests built into "make test".  Right now these rely on some of my infrastructure (ssh hosts, s3 buckets), so they should be generalized so other people can use them too.  Ideally to be run under CI.

**Comment by AmesCornish** [comment]
Regression test configuration has been pulled out into a "Makefile.inc".  You need to set up an S3 bucket and an SSH server to receive test backups.
