### ISSUE TITLE
empty directory for subvolume not copied over

### ISSUE THREAD

**Issue by simon196405** [AmesCornish/buttersink#8]
I have two subvolumes: root and /usr/portage.
When I use btrfs to make a snapshot of / there is an empty directory at /usr/portage.
When I copy this snapshot over with buttersink this empty directory is gone.

**Comment by AmesCornish** [comment]
Simon,

This is a "feature" of `btrfs send`, which buttersink uses to do the actual sending.  I think you'll see the same behavior if you use send directly, something like:

```
btrfs send /mysnapshot | ssh myremotehost btrfs receive /copyofmysnapshot
```

I'm actually not sure why btrfs does it this way.  If it's causing you problems you could ask about it on the [btrfs mailing list](https://www.mail-archive.com/linux-btrfs@vger.kernel.org/)

Thanks for the feedback!
